//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by slsvcutil, version 4.0.50826.0
// 
namespace ServiceReference.SITBusiness.Web.WService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseItem", Namespace="http://schemas.datacontract.org/2004/07/SITBusiness.Web")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.SITBusiness.Web.WService.child1))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.SITBusiness.Web.WService.child2))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference.SITBusiness.Web.WService.child3))]
    public partial class BaseItem : object
    {
        
        private string DescriptionField;
        
        private int IDField;
        
        private int lastchildField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int lastchild
        {
            get
            {
                return this.lastchildField;
            }
            set
            {
                this.lastchildField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="child1", Namespace="http://schemas.datacontract.org/2004/07/SITBusiness.Web")]
    public partial class child1 : ServiceReference.SITBusiness.Web.WService.BaseItem
    {
        
        private ServiceReference.SITBusiness.Web.WService.child2[] listchild1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.SITBusiness.Web.WService.child2[] listchild1
        {
            get
            {
                return this.listchild1Field;
            }
            set
            {
                this.listchild1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="child2", Namespace="http://schemas.datacontract.org/2004/07/SITBusiness.Web")]
    public partial class child2 : ServiceReference.SITBusiness.Web.WService.BaseItem
    {
        
        private ServiceReference.SITBusiness.Web.WService.child3[] listchild2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.SITBusiness.Web.WService.child3[] listchild2
        {
            get
            {
                return this.listchild2Field;
            }
            set
            {
                this.listchild2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="child3", Namespace="http://schemas.datacontract.org/2004/07/SITBusiness.Web")]
    public partial class child3 : ServiceReference.SITBusiness.Web.WService.BaseItem
    {
        
        private ServiceReference.SITBusiness.Web.WService.BaseItem[] listchild3Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.SITBusiness.Web.WService.BaseItem[] listchild3
        {
            get
            {
                return this.listchild3Field;
            }
            set
            {
                this.listchild3Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PassportType", Namespace="http://schemas.datacontract.org/2004/07/SITBusiness.Web")]
    public partial class PassportType : object
    {
        
        private string DevDescrRUField;
        
        private int DevIDField;
        
        private string DevInvNoField;
        
        private string DevModelNameField;
        
        private string DevModificationField;
        
        private string DevPassportNoField;
        
        private string DevSubModelField;
        
        private System.DateTime ImplementationDateField;
        
        private System.DateTime ProduceDateField;
        
        private string ProducerCityField;
        
        private string ProducerCountryField;
        
        private string ProducerNameField;
        
        private string ProducerPhoneField;
        
        private string ProducerStateField;
        
        private string ProducerStreetBildingField;
        
        private System.DateTime PurchaseDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevDescrRU
        {
            get
            {
                return this.DevDescrRUField;
            }
            set
            {
                this.DevDescrRUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DevID
        {
            get
            {
                return this.DevIDField;
            }
            set
            {
                this.DevIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevInvNo
        {
            get
            {
                return this.DevInvNoField;
            }
            set
            {
                this.DevInvNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevModelName
        {
            get
            {
                return this.DevModelNameField;
            }
            set
            {
                this.DevModelNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevModification
        {
            get
            {
                return this.DevModificationField;
            }
            set
            {
                this.DevModificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevPassportNo
        {
            get
            {
                return this.DevPassportNoField;
            }
            set
            {
                this.DevPassportNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevSubModel
        {
            get
            {
                return this.DevSubModelField;
            }
            set
            {
                this.DevSubModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ImplementationDate
        {
            get
            {
                return this.ImplementationDateField;
            }
            set
            {
                this.ImplementationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ProduceDate
        {
            get
            {
                return this.ProduceDateField;
            }
            set
            {
                this.ProduceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerCity
        {
            get
            {
                return this.ProducerCityField;
            }
            set
            {
                this.ProducerCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerCountry
        {
            get
            {
                return this.ProducerCountryField;
            }
            set
            {
                this.ProducerCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerName
        {
            get
            {
                return this.ProducerNameField;
            }
            set
            {
                this.ProducerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerPhone
        {
            get
            {
                return this.ProducerPhoneField;
            }
            set
            {
                this.ProducerPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerState
        {
            get
            {
                return this.ProducerStateField;
            }
            set
            {
                this.ProducerStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerStreetBilding
        {
            get
            {
                return this.ProducerStreetBildingField;
            }
            set
            {
                this.ProducerStreetBildingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PurchaseDate
        {
            get
            {
                return this.PurchaseDateField;
            }
            set
            {
                this.PurchaseDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parent", Namespace="http://schemas.datacontract.org/2004/07/SITBusiness.Web")]
    public partial class Parent : object
    {
        
        private ServiceReference.SITBusiness.Web.WService.child1[] ListChildField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.SITBusiness.Web.WService.child1[] ListChild
        {
            get
            {
                return this.ListChildField;
            }
            set
            {
                this.ListChildField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference.SITBusiness.Web.WService.WService")]
    public interface WService
    {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WService/TestService", ReplyAction="urn:WService/TestServiceResponse")]
        System.IAsyncResult BeginTestService(System.AsyncCallback callback, object asyncState);
        
        int EndTestService(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WService/WS_TestConnection", ReplyAction="urn:WService/WS_TestConnectionResponse")]
        System.IAsyncResult BeginWS_TestConnection(System.AsyncCallback callback, object asyncState);
        
        ServiceReference.SITBusiness.Web.WService.BaseItem EndWS_TestConnection(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WService/WS_TestAuthConnection", ReplyAction="urn:WService/WS_TestAuthConnectionResponse")]
        System.IAsyncResult BeginWS_TestAuthConnection(System.AsyncCallback callback, object asyncState);
        
        ServiceReference.SITBusiness.Web.WService.BaseItem EndWS_TestAuthConnection(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WService/WS_GetTree", ReplyAction="urn:WService/WS_GetTreeResponse")]
        System.IAsyncResult BeginWS_GetTree(System.AsyncCallback callback, object asyncState);
        
        ServiceReference.SITBusiness.Web.WService.child1[] EndWS_GetTree(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WService/WS_GetDevices", ReplyAction="urn:WService/WS_GetDevicesResponse")]
        System.IAsyncResult BeginWS_GetDevices(int ID, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.SITBusiness.Web.WService.BaseItem[] EndWS_GetDevices(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WService/WS_GetPassport", ReplyAction="urn:WService/WS_GetPassportResponse")]
        System.IAsyncResult BeginWS_GetPassport(int ID, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.SITBusiness.Web.WService.PassportType EndWS_GetPassport(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WService/WS_INSERT_PASSPORT", ReplyAction="urn:WService/WS_INSERT_PASSPORTResponse")]
        System.IAsyncResult BeginWS_INSERT_PASSPORT(ServiceReference.SITBusiness.Web.WService.PassportType p, int ID, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.SITBusiness.Web.WService.BaseItem EndWS_INSERT_PASSPORT(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WService/WS_Parent", ReplyAction="urn:WService/WS_ParentResponse")]
        System.IAsyncResult BeginWS_Parent(System.AsyncCallback callback, object asyncState);
        
        ServiceReference.SITBusiness.Web.WService.Parent EndWS_Parent(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WService/WS_Get_Child_1_Nodes", ReplyAction="urn:WService/WS_Get_Child_1_NodesResponse")]
        System.IAsyncResult BeginWS_Get_Child_1_Nodes(System.AsyncCallback callback, object asyncState);
        
        ServiceReference.SITBusiness.Web.WService.child1[] EndWS_Get_Child_1_Nodes(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WService/WS_Get_Child_2_Nodes", ReplyAction="urn:WService/WS_Get_Child_2_NodesResponse")]
        System.IAsyncResult BeginWS_Get_Child_2_Nodes(int ID, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.SITBusiness.Web.WService.child2[] EndWS_Get_Child_2_Nodes(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:WService/WS_Get_Child_3_Nodes", ReplyAction="urn:WService/WS_Get_Child_3_NodesResponse")]
        System.IAsyncResult BeginWS_Get_Child_3_Nodes(int ID_parent, int ID_child, System.AsyncCallback callback, object asyncState);
        
        ServiceReference.SITBusiness.Web.WService.child3[] EndWS_Get_Child_3_Nodes(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WServiceChannel : ServiceReference.SITBusiness.Web.WService.WService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public TestServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public int Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_TestConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public WS_TestConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.SITBusiness.Web.WService.BaseItem Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.SITBusiness.Web.WService.BaseItem)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_TestAuthConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public WS_TestAuthConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.SITBusiness.Web.WService.BaseItem Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.SITBusiness.Web.WService.BaseItem)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_GetTreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public WS_GetTreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.SITBusiness.Web.WService.child1[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.SITBusiness.Web.WService.child1[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_GetDevicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public WS_GetDevicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.SITBusiness.Web.WService.BaseItem[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.SITBusiness.Web.WService.BaseItem[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_GetPassportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public WS_GetPassportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.SITBusiness.Web.WService.PassportType Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.SITBusiness.Web.WService.PassportType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_INSERT_PASSPORTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public WS_INSERT_PASSPORTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.SITBusiness.Web.WService.BaseItem Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.SITBusiness.Web.WService.BaseItem)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_ParentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public WS_ParentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.SITBusiness.Web.WService.Parent Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.SITBusiness.Web.WService.Parent)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_Get_Child_1_NodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public WS_Get_Child_1_NodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.SITBusiness.Web.WService.child1[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.SITBusiness.Web.WService.child1[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_Get_Child_2_NodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public WS_Get_Child_2_NodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.SITBusiness.Web.WService.child2[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.SITBusiness.Web.WService.child2[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_Get_Child_3_NodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public WS_Get_Child_3_NodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public ServiceReference.SITBusiness.Web.WService.child3[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((ServiceReference.SITBusiness.Web.WService.child3[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WServiceClient : System.ServiceModel.ClientBase<ServiceReference.SITBusiness.Web.WService.WService>, ServiceReference.SITBusiness.Web.WService.WService
    {
        
        private BeginOperationDelegate onBeginTestServiceDelegate;
        
        private EndOperationDelegate onEndTestServiceDelegate;
        
        private System.Threading.SendOrPostCallback onTestServiceCompletedDelegate;
        
        private BeginOperationDelegate onBeginWS_TestConnectionDelegate;
        
        private EndOperationDelegate onEndWS_TestConnectionDelegate;
        
        private System.Threading.SendOrPostCallback onWS_TestConnectionCompletedDelegate;
        
        private BeginOperationDelegate onBeginWS_TestAuthConnectionDelegate;
        
        private EndOperationDelegate onEndWS_TestAuthConnectionDelegate;
        
        private System.Threading.SendOrPostCallback onWS_TestAuthConnectionCompletedDelegate;
        
        private BeginOperationDelegate onBeginWS_GetTreeDelegate;
        
        private EndOperationDelegate onEndWS_GetTreeDelegate;
        
        private System.Threading.SendOrPostCallback onWS_GetTreeCompletedDelegate;
        
        private BeginOperationDelegate onBeginWS_GetDevicesDelegate;
        
        private EndOperationDelegate onEndWS_GetDevicesDelegate;
        
        private System.Threading.SendOrPostCallback onWS_GetDevicesCompletedDelegate;
        
        private BeginOperationDelegate onBeginWS_GetPassportDelegate;
        
        private EndOperationDelegate onEndWS_GetPassportDelegate;
        
        private System.Threading.SendOrPostCallback onWS_GetPassportCompletedDelegate;
        
        private BeginOperationDelegate onBeginWS_INSERT_PASSPORTDelegate;
        
        private EndOperationDelegate onEndWS_INSERT_PASSPORTDelegate;
        
        private System.Threading.SendOrPostCallback onWS_INSERT_PASSPORTCompletedDelegate;
        
        private BeginOperationDelegate onBeginWS_ParentDelegate;
        
        private EndOperationDelegate onEndWS_ParentDelegate;
        
        private System.Threading.SendOrPostCallback onWS_ParentCompletedDelegate;
        
        private BeginOperationDelegate onBeginWS_Get_Child_1_NodesDelegate;
        
        private EndOperationDelegate onEndWS_Get_Child_1_NodesDelegate;
        
        private System.Threading.SendOrPostCallback onWS_Get_Child_1_NodesCompletedDelegate;
        
        private BeginOperationDelegate onBeginWS_Get_Child_2_NodesDelegate;
        
        private EndOperationDelegate onEndWS_Get_Child_2_NodesDelegate;
        
        private System.Threading.SendOrPostCallback onWS_Get_Child_2_NodesCompletedDelegate;
        
        private BeginOperationDelegate onBeginWS_Get_Child_3_NodesDelegate;
        
        private EndOperationDelegate onEndWS_Get_Child_3_NodesDelegate;
        
        private System.Threading.SendOrPostCallback onWS_Get_Child_3_NodesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WServiceClient()
        {
        }
        
        public WServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Net.CookieContainer CookieContainer
        {
            get
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    return httpCookieContainerManager.CookieContainer;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else
                {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<TestServiceCompletedEventArgs> TestServiceCompleted;
        
        public event System.EventHandler<WS_TestConnectionCompletedEventArgs> WS_TestConnectionCompleted;
        
        public event System.EventHandler<WS_TestAuthConnectionCompletedEventArgs> WS_TestAuthConnectionCompleted;
        
        public event System.EventHandler<WS_GetTreeCompletedEventArgs> WS_GetTreeCompleted;
        
        public event System.EventHandler<WS_GetDevicesCompletedEventArgs> WS_GetDevicesCompleted;
        
        public event System.EventHandler<WS_GetPassportCompletedEventArgs> WS_GetPassportCompleted;
        
        public event System.EventHandler<WS_INSERT_PASSPORTCompletedEventArgs> WS_INSERT_PASSPORTCompleted;
        
        public event System.EventHandler<WS_ParentCompletedEventArgs> WS_ParentCompleted;
        
        public event System.EventHandler<WS_Get_Child_1_NodesCompletedEventArgs> WS_Get_Child_1_NodesCompleted;
        
        public event System.EventHandler<WS_Get_Child_2_NodesCompletedEventArgs> WS_Get_Child_2_NodesCompleted;
        
        public event System.EventHandler<WS_Get_Child_3_NodesCompletedEventArgs> WS_Get_Child_3_NodesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.SITBusiness.Web.WService.WService.BeginTestService(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginTestService(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int ServiceReference.SITBusiness.Web.WService.WService.EndTestService(System.IAsyncResult result)
        {
            return base.Channel.EndTestService(result);
        }
        
        private System.IAsyncResult OnBeginTestService(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((ServiceReference.SITBusiness.Web.WService.WService)(this)).BeginTestService(callback, asyncState);
        }
        
        private object[] OnEndTestService(System.IAsyncResult result)
        {
            int retVal = ((ServiceReference.SITBusiness.Web.WService.WService)(this)).EndTestService(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTestServiceCompleted(object state)
        {
            if ((this.TestServiceCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TestServiceCompleted(this, new TestServiceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TestServiceAsync()
        {
            this.TestServiceAsync(null);
        }
        
        public void TestServiceAsync(object userState)
        {
            if ((this.onBeginTestServiceDelegate == null))
            {
                this.onBeginTestServiceDelegate = new BeginOperationDelegate(this.OnBeginTestService);
            }
            if ((this.onEndTestServiceDelegate == null))
            {
                this.onEndTestServiceDelegate = new EndOperationDelegate(this.OnEndTestService);
            }
            if ((this.onTestServiceCompletedDelegate == null))
            {
                this.onTestServiceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTestServiceCompleted);
            }
            base.InvokeAsync(this.onBeginTestServiceDelegate, null, this.onEndTestServiceDelegate, this.onTestServiceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.SITBusiness.Web.WService.WService.BeginWS_TestConnection(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginWS_TestConnection(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.SITBusiness.Web.WService.BaseItem ServiceReference.SITBusiness.Web.WService.WService.EndWS_TestConnection(System.IAsyncResult result)
        {
            return base.Channel.EndWS_TestConnection(result);
        }
        
        private System.IAsyncResult OnBeginWS_TestConnection(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((ServiceReference.SITBusiness.Web.WService.WService)(this)).BeginWS_TestConnection(callback, asyncState);
        }
        
        private object[] OnEndWS_TestConnection(System.IAsyncResult result)
        {
            ServiceReference.SITBusiness.Web.WService.BaseItem retVal = ((ServiceReference.SITBusiness.Web.WService.WService)(this)).EndWS_TestConnection(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWS_TestConnectionCompleted(object state)
        {
            if ((this.WS_TestConnectionCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WS_TestConnectionCompleted(this, new WS_TestConnectionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WS_TestConnectionAsync()
        {
            this.WS_TestConnectionAsync(null);
        }
        
        public void WS_TestConnectionAsync(object userState)
        {
            if ((this.onBeginWS_TestConnectionDelegate == null))
            {
                this.onBeginWS_TestConnectionDelegate = new BeginOperationDelegate(this.OnBeginWS_TestConnection);
            }
            if ((this.onEndWS_TestConnectionDelegate == null))
            {
                this.onEndWS_TestConnectionDelegate = new EndOperationDelegate(this.OnEndWS_TestConnection);
            }
            if ((this.onWS_TestConnectionCompletedDelegate == null))
            {
                this.onWS_TestConnectionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWS_TestConnectionCompleted);
            }
            base.InvokeAsync(this.onBeginWS_TestConnectionDelegate, null, this.onEndWS_TestConnectionDelegate, this.onWS_TestConnectionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.SITBusiness.Web.WService.WService.BeginWS_TestAuthConnection(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginWS_TestAuthConnection(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.SITBusiness.Web.WService.BaseItem ServiceReference.SITBusiness.Web.WService.WService.EndWS_TestAuthConnection(System.IAsyncResult result)
        {
            return base.Channel.EndWS_TestAuthConnection(result);
        }
        
        private System.IAsyncResult OnBeginWS_TestAuthConnection(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((ServiceReference.SITBusiness.Web.WService.WService)(this)).BeginWS_TestAuthConnection(callback, asyncState);
        }
        
        private object[] OnEndWS_TestAuthConnection(System.IAsyncResult result)
        {
            ServiceReference.SITBusiness.Web.WService.BaseItem retVal = ((ServiceReference.SITBusiness.Web.WService.WService)(this)).EndWS_TestAuthConnection(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWS_TestAuthConnectionCompleted(object state)
        {
            if ((this.WS_TestAuthConnectionCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WS_TestAuthConnectionCompleted(this, new WS_TestAuthConnectionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WS_TestAuthConnectionAsync()
        {
            this.WS_TestAuthConnectionAsync(null);
        }
        
        public void WS_TestAuthConnectionAsync(object userState)
        {
            if ((this.onBeginWS_TestAuthConnectionDelegate == null))
            {
                this.onBeginWS_TestAuthConnectionDelegate = new BeginOperationDelegate(this.OnBeginWS_TestAuthConnection);
            }
            if ((this.onEndWS_TestAuthConnectionDelegate == null))
            {
                this.onEndWS_TestAuthConnectionDelegate = new EndOperationDelegate(this.OnEndWS_TestAuthConnection);
            }
            if ((this.onWS_TestAuthConnectionCompletedDelegate == null))
            {
                this.onWS_TestAuthConnectionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWS_TestAuthConnectionCompleted);
            }
            base.InvokeAsync(this.onBeginWS_TestAuthConnectionDelegate, null, this.onEndWS_TestAuthConnectionDelegate, this.onWS_TestAuthConnectionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.SITBusiness.Web.WService.WService.BeginWS_GetTree(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginWS_GetTree(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.SITBusiness.Web.WService.child1[] ServiceReference.SITBusiness.Web.WService.WService.EndWS_GetTree(System.IAsyncResult result)
        {
            return base.Channel.EndWS_GetTree(result);
        }
        
        private System.IAsyncResult OnBeginWS_GetTree(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((ServiceReference.SITBusiness.Web.WService.WService)(this)).BeginWS_GetTree(callback, asyncState);
        }
        
        private object[] OnEndWS_GetTree(System.IAsyncResult result)
        {
            ServiceReference.SITBusiness.Web.WService.child1[] retVal = ((ServiceReference.SITBusiness.Web.WService.WService)(this)).EndWS_GetTree(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWS_GetTreeCompleted(object state)
        {
            if ((this.WS_GetTreeCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WS_GetTreeCompleted(this, new WS_GetTreeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WS_GetTreeAsync()
        {
            this.WS_GetTreeAsync(null);
        }
        
        public void WS_GetTreeAsync(object userState)
        {
            if ((this.onBeginWS_GetTreeDelegate == null))
            {
                this.onBeginWS_GetTreeDelegate = new BeginOperationDelegate(this.OnBeginWS_GetTree);
            }
            if ((this.onEndWS_GetTreeDelegate == null))
            {
                this.onEndWS_GetTreeDelegate = new EndOperationDelegate(this.OnEndWS_GetTree);
            }
            if ((this.onWS_GetTreeCompletedDelegate == null))
            {
                this.onWS_GetTreeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWS_GetTreeCompleted);
            }
            base.InvokeAsync(this.onBeginWS_GetTreeDelegate, null, this.onEndWS_GetTreeDelegate, this.onWS_GetTreeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.SITBusiness.Web.WService.WService.BeginWS_GetDevices(int ID, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginWS_GetDevices(ID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.SITBusiness.Web.WService.BaseItem[] ServiceReference.SITBusiness.Web.WService.WService.EndWS_GetDevices(System.IAsyncResult result)
        {
            return base.Channel.EndWS_GetDevices(result);
        }
        
        private System.IAsyncResult OnBeginWS_GetDevices(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int ID = ((int)(inValues[0]));
            return ((ServiceReference.SITBusiness.Web.WService.WService)(this)).BeginWS_GetDevices(ID, callback, asyncState);
        }
        
        private object[] OnEndWS_GetDevices(System.IAsyncResult result)
        {
            ServiceReference.SITBusiness.Web.WService.BaseItem[] retVal = ((ServiceReference.SITBusiness.Web.WService.WService)(this)).EndWS_GetDevices(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWS_GetDevicesCompleted(object state)
        {
            if ((this.WS_GetDevicesCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WS_GetDevicesCompleted(this, new WS_GetDevicesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WS_GetDevicesAsync(int ID)
        {
            this.WS_GetDevicesAsync(ID, null);
        }
        
        public void WS_GetDevicesAsync(int ID, object userState)
        {
            if ((this.onBeginWS_GetDevicesDelegate == null))
            {
                this.onBeginWS_GetDevicesDelegate = new BeginOperationDelegate(this.OnBeginWS_GetDevices);
            }
            if ((this.onEndWS_GetDevicesDelegate == null))
            {
                this.onEndWS_GetDevicesDelegate = new EndOperationDelegate(this.OnEndWS_GetDevices);
            }
            if ((this.onWS_GetDevicesCompletedDelegate == null))
            {
                this.onWS_GetDevicesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWS_GetDevicesCompleted);
            }
            base.InvokeAsync(this.onBeginWS_GetDevicesDelegate, new object[] {
                        ID}, this.onEndWS_GetDevicesDelegate, this.onWS_GetDevicesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.SITBusiness.Web.WService.WService.BeginWS_GetPassport(int ID, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginWS_GetPassport(ID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.SITBusiness.Web.WService.PassportType ServiceReference.SITBusiness.Web.WService.WService.EndWS_GetPassport(System.IAsyncResult result)
        {
            return base.Channel.EndWS_GetPassport(result);
        }
        
        private System.IAsyncResult OnBeginWS_GetPassport(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int ID = ((int)(inValues[0]));
            return ((ServiceReference.SITBusiness.Web.WService.WService)(this)).BeginWS_GetPassport(ID, callback, asyncState);
        }
        
        private object[] OnEndWS_GetPassport(System.IAsyncResult result)
        {
            ServiceReference.SITBusiness.Web.WService.PassportType retVal = ((ServiceReference.SITBusiness.Web.WService.WService)(this)).EndWS_GetPassport(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWS_GetPassportCompleted(object state)
        {
            if ((this.WS_GetPassportCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WS_GetPassportCompleted(this, new WS_GetPassportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WS_GetPassportAsync(int ID)
        {
            this.WS_GetPassportAsync(ID, null);
        }
        
        public void WS_GetPassportAsync(int ID, object userState)
        {
            if ((this.onBeginWS_GetPassportDelegate == null))
            {
                this.onBeginWS_GetPassportDelegate = new BeginOperationDelegate(this.OnBeginWS_GetPassport);
            }
            if ((this.onEndWS_GetPassportDelegate == null))
            {
                this.onEndWS_GetPassportDelegate = new EndOperationDelegate(this.OnEndWS_GetPassport);
            }
            if ((this.onWS_GetPassportCompletedDelegate == null))
            {
                this.onWS_GetPassportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWS_GetPassportCompleted);
            }
            base.InvokeAsync(this.onBeginWS_GetPassportDelegate, new object[] {
                        ID}, this.onEndWS_GetPassportDelegate, this.onWS_GetPassportCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.SITBusiness.Web.WService.WService.BeginWS_INSERT_PASSPORT(ServiceReference.SITBusiness.Web.WService.PassportType p, int ID, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginWS_INSERT_PASSPORT(p, ID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.SITBusiness.Web.WService.BaseItem ServiceReference.SITBusiness.Web.WService.WService.EndWS_INSERT_PASSPORT(System.IAsyncResult result)
        {
            return base.Channel.EndWS_INSERT_PASSPORT(result);
        }
        
        private System.IAsyncResult OnBeginWS_INSERT_PASSPORT(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            ServiceReference.SITBusiness.Web.WService.PassportType p = ((ServiceReference.SITBusiness.Web.WService.PassportType)(inValues[0]));
            int ID = ((int)(inValues[1]));
            return ((ServiceReference.SITBusiness.Web.WService.WService)(this)).BeginWS_INSERT_PASSPORT(p, ID, callback, asyncState);
        }
        
        private object[] OnEndWS_INSERT_PASSPORT(System.IAsyncResult result)
        {
            ServiceReference.SITBusiness.Web.WService.BaseItem retVal = ((ServiceReference.SITBusiness.Web.WService.WService)(this)).EndWS_INSERT_PASSPORT(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWS_INSERT_PASSPORTCompleted(object state)
        {
            if ((this.WS_INSERT_PASSPORTCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WS_INSERT_PASSPORTCompleted(this, new WS_INSERT_PASSPORTCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WS_INSERT_PASSPORTAsync(ServiceReference.SITBusiness.Web.WService.PassportType p, int ID)
        {
            this.WS_INSERT_PASSPORTAsync(p, ID, null);
        }
        
        public void WS_INSERT_PASSPORTAsync(ServiceReference.SITBusiness.Web.WService.PassportType p, int ID, object userState)
        {
            if ((this.onBeginWS_INSERT_PASSPORTDelegate == null))
            {
                this.onBeginWS_INSERT_PASSPORTDelegate = new BeginOperationDelegate(this.OnBeginWS_INSERT_PASSPORT);
            }
            if ((this.onEndWS_INSERT_PASSPORTDelegate == null))
            {
                this.onEndWS_INSERT_PASSPORTDelegate = new EndOperationDelegate(this.OnEndWS_INSERT_PASSPORT);
            }
            if ((this.onWS_INSERT_PASSPORTCompletedDelegate == null))
            {
                this.onWS_INSERT_PASSPORTCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWS_INSERT_PASSPORTCompleted);
            }
            base.InvokeAsync(this.onBeginWS_INSERT_PASSPORTDelegate, new object[] {
                        p,
                        ID}, this.onEndWS_INSERT_PASSPORTDelegate, this.onWS_INSERT_PASSPORTCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.SITBusiness.Web.WService.WService.BeginWS_Parent(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginWS_Parent(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.SITBusiness.Web.WService.Parent ServiceReference.SITBusiness.Web.WService.WService.EndWS_Parent(System.IAsyncResult result)
        {
            return base.Channel.EndWS_Parent(result);
        }
        
        private System.IAsyncResult OnBeginWS_Parent(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((ServiceReference.SITBusiness.Web.WService.WService)(this)).BeginWS_Parent(callback, asyncState);
        }
        
        private object[] OnEndWS_Parent(System.IAsyncResult result)
        {
            ServiceReference.SITBusiness.Web.WService.Parent retVal = ((ServiceReference.SITBusiness.Web.WService.WService)(this)).EndWS_Parent(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWS_ParentCompleted(object state)
        {
            if ((this.WS_ParentCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WS_ParentCompleted(this, new WS_ParentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WS_ParentAsync()
        {
            this.WS_ParentAsync(null);
        }
        
        public void WS_ParentAsync(object userState)
        {
            if ((this.onBeginWS_ParentDelegate == null))
            {
                this.onBeginWS_ParentDelegate = new BeginOperationDelegate(this.OnBeginWS_Parent);
            }
            if ((this.onEndWS_ParentDelegate == null))
            {
                this.onEndWS_ParentDelegate = new EndOperationDelegate(this.OnEndWS_Parent);
            }
            if ((this.onWS_ParentCompletedDelegate == null))
            {
                this.onWS_ParentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWS_ParentCompleted);
            }
            base.InvokeAsync(this.onBeginWS_ParentDelegate, null, this.onEndWS_ParentDelegate, this.onWS_ParentCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.SITBusiness.Web.WService.WService.BeginWS_Get_Child_1_Nodes(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginWS_Get_Child_1_Nodes(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.SITBusiness.Web.WService.child1[] ServiceReference.SITBusiness.Web.WService.WService.EndWS_Get_Child_1_Nodes(System.IAsyncResult result)
        {
            return base.Channel.EndWS_Get_Child_1_Nodes(result);
        }
        
        private System.IAsyncResult OnBeginWS_Get_Child_1_Nodes(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((ServiceReference.SITBusiness.Web.WService.WService)(this)).BeginWS_Get_Child_1_Nodes(callback, asyncState);
        }
        
        private object[] OnEndWS_Get_Child_1_Nodes(System.IAsyncResult result)
        {
            ServiceReference.SITBusiness.Web.WService.child1[] retVal = ((ServiceReference.SITBusiness.Web.WService.WService)(this)).EndWS_Get_Child_1_Nodes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWS_Get_Child_1_NodesCompleted(object state)
        {
            if ((this.WS_Get_Child_1_NodesCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WS_Get_Child_1_NodesCompleted(this, new WS_Get_Child_1_NodesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WS_Get_Child_1_NodesAsync()
        {
            this.WS_Get_Child_1_NodesAsync(null);
        }
        
        public void WS_Get_Child_1_NodesAsync(object userState)
        {
            if ((this.onBeginWS_Get_Child_1_NodesDelegate == null))
            {
                this.onBeginWS_Get_Child_1_NodesDelegate = new BeginOperationDelegate(this.OnBeginWS_Get_Child_1_Nodes);
            }
            if ((this.onEndWS_Get_Child_1_NodesDelegate == null))
            {
                this.onEndWS_Get_Child_1_NodesDelegate = new EndOperationDelegate(this.OnEndWS_Get_Child_1_Nodes);
            }
            if ((this.onWS_Get_Child_1_NodesCompletedDelegate == null))
            {
                this.onWS_Get_Child_1_NodesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWS_Get_Child_1_NodesCompleted);
            }
            base.InvokeAsync(this.onBeginWS_Get_Child_1_NodesDelegate, null, this.onEndWS_Get_Child_1_NodesDelegate, this.onWS_Get_Child_1_NodesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.SITBusiness.Web.WService.WService.BeginWS_Get_Child_2_Nodes(int ID, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginWS_Get_Child_2_Nodes(ID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.SITBusiness.Web.WService.child2[] ServiceReference.SITBusiness.Web.WService.WService.EndWS_Get_Child_2_Nodes(System.IAsyncResult result)
        {
            return base.Channel.EndWS_Get_Child_2_Nodes(result);
        }
        
        private System.IAsyncResult OnBeginWS_Get_Child_2_Nodes(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int ID = ((int)(inValues[0]));
            return ((ServiceReference.SITBusiness.Web.WService.WService)(this)).BeginWS_Get_Child_2_Nodes(ID, callback, asyncState);
        }
        
        private object[] OnEndWS_Get_Child_2_Nodes(System.IAsyncResult result)
        {
            ServiceReference.SITBusiness.Web.WService.child2[] retVal = ((ServiceReference.SITBusiness.Web.WService.WService)(this)).EndWS_Get_Child_2_Nodes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWS_Get_Child_2_NodesCompleted(object state)
        {
            if ((this.WS_Get_Child_2_NodesCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WS_Get_Child_2_NodesCompleted(this, new WS_Get_Child_2_NodesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WS_Get_Child_2_NodesAsync(int ID)
        {
            this.WS_Get_Child_2_NodesAsync(ID, null);
        }
        
        public void WS_Get_Child_2_NodesAsync(int ID, object userState)
        {
            if ((this.onBeginWS_Get_Child_2_NodesDelegate == null))
            {
                this.onBeginWS_Get_Child_2_NodesDelegate = new BeginOperationDelegate(this.OnBeginWS_Get_Child_2_Nodes);
            }
            if ((this.onEndWS_Get_Child_2_NodesDelegate == null))
            {
                this.onEndWS_Get_Child_2_NodesDelegate = new EndOperationDelegate(this.OnEndWS_Get_Child_2_Nodes);
            }
            if ((this.onWS_Get_Child_2_NodesCompletedDelegate == null))
            {
                this.onWS_Get_Child_2_NodesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWS_Get_Child_2_NodesCompleted);
            }
            base.InvokeAsync(this.onBeginWS_Get_Child_2_NodesDelegate, new object[] {
                        ID}, this.onEndWS_Get_Child_2_NodesDelegate, this.onWS_Get_Child_2_NodesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ServiceReference.SITBusiness.Web.WService.WService.BeginWS_Get_Child_3_Nodes(int ID_parent, int ID_child, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginWS_Get_Child_3_Nodes(ID_parent, ID_child, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.SITBusiness.Web.WService.child3[] ServiceReference.SITBusiness.Web.WService.WService.EndWS_Get_Child_3_Nodes(System.IAsyncResult result)
        {
            return base.Channel.EndWS_Get_Child_3_Nodes(result);
        }
        
        private System.IAsyncResult OnBeginWS_Get_Child_3_Nodes(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int ID_parent = ((int)(inValues[0]));
            int ID_child = ((int)(inValues[1]));
            return ((ServiceReference.SITBusiness.Web.WService.WService)(this)).BeginWS_Get_Child_3_Nodes(ID_parent, ID_child, callback, asyncState);
        }
        
        private object[] OnEndWS_Get_Child_3_Nodes(System.IAsyncResult result)
        {
            ServiceReference.SITBusiness.Web.WService.child3[] retVal = ((ServiceReference.SITBusiness.Web.WService.WService)(this)).EndWS_Get_Child_3_Nodes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWS_Get_Child_3_NodesCompleted(object state)
        {
            if ((this.WS_Get_Child_3_NodesCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WS_Get_Child_3_NodesCompleted(this, new WS_Get_Child_3_NodesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WS_Get_Child_3_NodesAsync(int ID_parent, int ID_child)
        {
            this.WS_Get_Child_3_NodesAsync(ID_parent, ID_child, null);
        }
        
        public void WS_Get_Child_3_NodesAsync(int ID_parent, int ID_child, object userState)
        {
            if ((this.onBeginWS_Get_Child_3_NodesDelegate == null))
            {
                this.onBeginWS_Get_Child_3_NodesDelegate = new BeginOperationDelegate(this.OnBeginWS_Get_Child_3_Nodes);
            }
            if ((this.onEndWS_Get_Child_3_NodesDelegate == null))
            {
                this.onEndWS_Get_Child_3_NodesDelegate = new EndOperationDelegate(this.OnEndWS_Get_Child_3_Nodes);
            }
            if ((this.onWS_Get_Child_3_NodesCompletedDelegate == null))
            {
                this.onWS_Get_Child_3_NodesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWS_Get_Child_3_NodesCompleted);
            }
            base.InvokeAsync(this.onBeginWS_Get_Child_3_NodesDelegate, new object[] {
                        ID_parent,
                        ID_child}, this.onEndWS_Get_Child_3_NodesDelegate, this.onWS_Get_Child_3_NodesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state)
        {
            if ((this.OpenCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync()
        {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState)
        {
            if ((this.onBeginOpenDelegate == null))
            {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null))
            {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null))
            {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state)
        {
            if ((this.CloseCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync()
        {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState)
        {
            if ((this.onBeginCloseDelegate == null))
            {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null))
            {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null))
            {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ServiceReference.SITBusiness.Web.WService.WService CreateChannel()
        {
            return new WServiceClientChannel(this);
        }
        
        private class WServiceClientChannel : ChannelBase<ServiceReference.SITBusiness.Web.WService.WService>, ServiceReference.SITBusiness.Web.WService.WService
        {
            
            public WServiceClientChannel(System.ServiceModel.ClientBase<ServiceReference.SITBusiness.Web.WService.WService> client) : 
                    base(client)
            {
            }
            
            public System.IAsyncResult BeginTestService(System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("TestService", _args, callback, asyncState);
                return _result;
            }
            
            public int EndTestService(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("TestService", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginWS_TestConnection(System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("WS_TestConnection", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.SITBusiness.Web.WService.BaseItem EndWS_TestConnection(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.SITBusiness.Web.WService.BaseItem _result = ((ServiceReference.SITBusiness.Web.WService.BaseItem)(base.EndInvoke("WS_TestConnection", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginWS_TestAuthConnection(System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("WS_TestAuthConnection", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.SITBusiness.Web.WService.BaseItem EndWS_TestAuthConnection(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.SITBusiness.Web.WService.BaseItem _result = ((ServiceReference.SITBusiness.Web.WService.BaseItem)(base.EndInvoke("WS_TestAuthConnection", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginWS_GetTree(System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("WS_GetTree", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.SITBusiness.Web.WService.child1[] EndWS_GetTree(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.SITBusiness.Web.WService.child1[] _result = ((ServiceReference.SITBusiness.Web.WService.child1[])(base.EndInvoke("WS_GetTree", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginWS_GetDevices(int ID, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = ID;
                System.IAsyncResult _result = base.BeginInvoke("WS_GetDevices", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.SITBusiness.Web.WService.BaseItem[] EndWS_GetDevices(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.SITBusiness.Web.WService.BaseItem[] _result = ((ServiceReference.SITBusiness.Web.WService.BaseItem[])(base.EndInvoke("WS_GetDevices", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginWS_GetPassport(int ID, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = ID;
                System.IAsyncResult _result = base.BeginInvoke("WS_GetPassport", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.SITBusiness.Web.WService.PassportType EndWS_GetPassport(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.SITBusiness.Web.WService.PassportType _result = ((ServiceReference.SITBusiness.Web.WService.PassportType)(base.EndInvoke("WS_GetPassport", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginWS_INSERT_PASSPORT(ServiceReference.SITBusiness.Web.WService.PassportType p, int ID, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[2];
                _args[0] = p;
                _args[1] = ID;
                System.IAsyncResult _result = base.BeginInvoke("WS_INSERT_PASSPORT", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.SITBusiness.Web.WService.BaseItem EndWS_INSERT_PASSPORT(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.SITBusiness.Web.WService.BaseItem _result = ((ServiceReference.SITBusiness.Web.WService.BaseItem)(base.EndInvoke("WS_INSERT_PASSPORT", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginWS_Parent(System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("WS_Parent", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.SITBusiness.Web.WService.Parent EndWS_Parent(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.SITBusiness.Web.WService.Parent _result = ((ServiceReference.SITBusiness.Web.WService.Parent)(base.EndInvoke("WS_Parent", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginWS_Get_Child_1_Nodes(System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("WS_Get_Child_1_Nodes", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.SITBusiness.Web.WService.child1[] EndWS_Get_Child_1_Nodes(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.SITBusiness.Web.WService.child1[] _result = ((ServiceReference.SITBusiness.Web.WService.child1[])(base.EndInvoke("WS_Get_Child_1_Nodes", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginWS_Get_Child_2_Nodes(int ID, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = ID;
                System.IAsyncResult _result = base.BeginInvoke("WS_Get_Child_2_Nodes", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.SITBusiness.Web.WService.child2[] EndWS_Get_Child_2_Nodes(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.SITBusiness.Web.WService.child2[] _result = ((ServiceReference.SITBusiness.Web.WService.child2[])(base.EndInvoke("WS_Get_Child_2_Nodes", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginWS_Get_Child_3_Nodes(int ID_parent, int ID_child, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[2];
                _args[0] = ID_parent;
                _args[1] = ID_child;
                System.IAsyncResult _result = base.BeginInvoke("WS_Get_Child_3_Nodes", _args, callback, asyncState);
                return _result;
            }
            
            public ServiceReference.SITBusiness.Web.WService.child3[] EndWS_Get_Child_3_Nodes(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                ServiceReference.SITBusiness.Web.WService.child3[] _result = ((ServiceReference.SITBusiness.Web.WService.child3[])(base.EndInvoke("WS_Get_Child_3_Nodes", _args, result)));
                return _result;
            }
        }
    }
}
// Auto generated configuration elements
// Generated client configuration:CustomBinding_WService<>http://WService.svc<>http://localhost:8080/WService.svc
