//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITBusiness {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SITBusiness.Assets.Resources.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A user name for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string CreateUserStatusDuplicateEmail {
            get {
                return ResourceManager.GetString("CreateUserStatusDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User name already exists. Please enter a different user name..
        /// </summary>
        public static string CreateUserStatusDuplicateUserName {
            get {
                return ResourceManager.GetString("CreateUserStatusDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string CreateUserStatusFailed {
            get {
                return ResourceManager.GetString("CreateUserStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка работы с СУБД.
        /// </summary>
        public static string err_DB {
            get {
                return ResourceManager.GetString("err_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка удаления данных (DELETE).
        /// </summary>
        public static string err_DELETE {
            get {
                return ResourceManager.GetString("err_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка вставки данных (INSERT).
        /// </summary>
        public static string err_INSERT {
            get {
                return ResourceManager.GetString("err_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка получения данных (SELECT).
        /// </summary>
        public static string err_SELECT {
            get {
                return ResourceManager.GetString("err_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная ошибка!.
        /// </summary>
        public static string err_UNKNOWN {
            get {
                return ResourceManager.GetString("err_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка обновления данных (UPDATE).
        /// </summary>
        public static string err_UPDATE {
            get {
                return ResourceManager.GetString("err_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The user name or password is incorrect.
        /// </summary>
        public static string ErrorBadUserNameOrPassword {
            get {
                return ResourceManager.GetString("ErrorBadUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration was successful but there was a problem while trying to log in with your credentials: {0}.
        /// </summary>
        public static string ErrorLoginAfterRegistrationFailed {
            get {
                return ResourceManager.GetString("ErrorLoginAfterRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error Details.
        /// </summary>
        public static string ErrorWindowErrorDetails {
            get {
                return ResourceManager.GetString("ErrorWindowErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An unknown error has occurred. Please contact your administrator for help..
        /// </summary>
        public static string ErrorWindowGenericError {
            get {
                return ResourceManager.GetString("ErrorWindowGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string ErrorWindowTitle {
            get {
                return ResourceManager.GetString("ErrorWindowTitle", resourceCulture);
            }
        }
    }
}
