//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITBusiness {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SITBusiness.Assets.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение выполнения операции.
        /// </summary>
        public static string m_Confirm {
            get {
                return ResourceManager.GetString("m_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение.
        /// </summary>
        public static string m_Message {
            get {
                return ResourceManager.GetString("m_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим просмотра.
        /// </summary>
        public static string m_modeR {
            get {
                return ResourceManager.GetString("m_modeR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим обновления.
        /// </summary>
        public static string m_modeU {
            get {
                return ResourceManager.GetString("m_modeU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим добавления.
        /// </summary>
        public static string m_modeW {
            get {
                return ResourceManager.GetString("m_modeW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция выполнена успешно.
        /// </summary>
        public static string m_OpSuccessfull {
            get {
                return ResourceManager.GetString("m_OpSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция не выполнена.
        /// </summary>
        public static string m_OpUnSuccessfull {
            get {
                return ResourceManager.GetString("m_OpUnSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Паспорт успешно добавлен.
        /// </summary>
        public static string m_PassportInserted {
            get {
                return ResourceManager.GetString("m_PassportInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно обновлены данные паспорта устройства.
        /// </summary>
        public static string m_PassportUpdated {
            get {
                return ResourceManager.GetString("m_PassportUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производитель успешно добавлен.
        /// </summary>
        public static string m_ProducerInserted {
            get {
                return ResourceManager.GetString("m_ProducerInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно обновлены данные производителя.
        /// </summary>
        public static string m_ProducerUpdated {
            get {
                return ResourceManager.GetString("m_ProducerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно обновлены данные производителя.
        /// </summary>
        public static string m_ProduserUpdated {
            get {
                return ResourceManager.GetString("m_ProduserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбран раздел в дереве устройств, в который нужно добавить устройство.
        /// </summary>
        public static string m_treeItemIsNotSelected {
            get {
                return ResourceManager.GetString("m_treeItemIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string m_Warning {
            get {
                return ResourceManager.GetString("m_Warning", resourceCulture);
            }
        }
    }
}
