//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITBusiness {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityQuestions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityQuestions() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SITBusiness.Assets.Resources.SecurityQuestions", typeof(SecurityQuestions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What is the name of your favorite childhood friend?.
        /// </summary>
        public static string BestChildhoodFriendQuestion {
            get {
                return ResourceManager.GetString("BestChildhoodFriendQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What was your childhood nickname?.
        /// </summary>
        public static string ChildhoodNicknameQuestion {
            get {
                return ResourceManager.GetString("ChildhoodNicknameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What was the color of your first car?.
        /// </summary>
        public static string FirstCarColorQuestion {
            get {
                return ResourceManager.GetString("FirstCarColorQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What was the make and model of your first car?.
        /// </summary>
        public static string FirstCarMakeAndModelQuestion {
            get {
                return ResourceManager.GetString("FirstCarMakeAndModelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In what city or town was your first job?.
        /// </summary>
        public static string FirstJobCityQuestion {
            get {
                return ResourceManager.GetString("FirstJobCityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Where did you vacation last year?.
        /// </summary>
        public static string LastVacationLocationQuestion {
            get {
                return ResourceManager.GetString("LastVacationLocationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What is your maternal grandmother&apos;s maiden name?.
        /// </summary>
        public static string MaternalGrandmothersMaidenNameQuestion {
            get {
                return ResourceManager.GetString("MaternalGrandmothersMaidenNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What is your mother&apos;s maiden name?.
        /// </summary>
        public static string MothersMaidenNameQuestion {
            get {
                return ResourceManager.GetString("MothersMaidenNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What is your pet&apos;s name?.
        /// </summary>
        public static string PetNameQuestion {
            get {
                return ResourceManager.GetString("PetNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What school did you attend for sixth grade?.
        /// </summary>
        public static string SixthGradeSchoolNameQuestion {
            get {
                return ResourceManager.GetString("SixthGradeSchoolNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In what year was your father born?.
        /// </summary>
        public static string YearFatherWasBornQuestion {
            get {
                return ResourceManager.GetString("YearFatherWasBornQuestion", resourceCulture);
            }
        }
    }
}
