//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT_Reports.WServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsDBTreeBase", Namespace="http://www.SITBusiness.com/SITBusiness_classLib/wsDBTreeBase")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIT_Reports.WServiceReference.DBTree))]
    public partial class wsDBTreeBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIT_Reports.WServiceReference.wsBaseItem[] DBDATAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIT_Reports.WServiceReference.wsBaseItem[] DBDATA {
            get {
                return this.DBDATAField;
            }
            set {
                if ((object.ReferenceEquals(this.DBDATAField, value) != true)) {
                    this.DBDATAField = value;
                    this.RaisePropertyChanged("DBDATA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DBTree", Namespace="http://schemas.datacontract.org/2004/07/SITBusiness.Web")]
    [System.SerializableAttribute()]
    public partial class DBTree : SIT_Reports.WServiceReference.wsDBTreeBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsBaseItem", Namespace="http://www.SITBusiness.com/SITBusiness_classLib/wsBaseItem")]
    [System.SerializableAttribute()]
    public partial class wsBaseItem : SIT_Reports.WServiceReference.wsSimpleItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCalibratedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCheckedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkToIconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCalibrated {
            get {
                return this.IsCalibratedField;
            }
            set {
                if ((this.IsCalibratedField.Equals(value) != true)) {
                    this.IsCalibratedField = value;
                    this.RaisePropertyChanged("IsCalibrated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChecked {
            get {
                return this.IsCheckedField;
            }
            set {
                if ((this.IsCheckedField.Equals(value) != true)) {
                    this.IsCheckedField = value;
                    this.RaisePropertyChanged("IsChecked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsType {
            get {
                return this.IsTypeField;
            }
            set {
                if ((this.IsTypeField.Equals(value) != true)) {
                    this.IsTypeField = value;
                    this.RaisePropertyChanged("IsType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkToIcon {
            get {
                return this.LinkToIconField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkToIconField, value) != true)) {
                    this.LinkToIconField = value;
                    this.RaisePropertyChanged("LinkToIcon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsSimpleItem", Namespace="http://www.SITBusiness.com/SITBusiness_classLib/wsSimpleItem")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIT_Reports.WServiceReference.wsWorkState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIT_Reports.WServiceReference.WStateNDuration))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIT_Reports.WServiceReference.wsProducerType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIT_Reports.WServiceReference.wsModelItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIT_Reports.WServiceReference.wsMaintenance))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIT_Reports.WServiceReference.wsCalibration))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SIT_Reports.WServiceReference.wsBaseItem))]
    public partial class wsSimpleItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsWorkState", Namespace="http://www.SITBusiness.com/SITBusiness_classLib/wsWorkState")]
    [System.SerializableAttribute()]
    public partial class wsWorkState : SIT_Reports.WServiceReference.wsSimpleItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime finishDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIT_Reports.WServiceReference.wsSimpleItem[] list_EDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIT_Reports.WServiceReference.WorkStateMessage[] list_SCADAMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIT_Reports.WServiceReference.WStateNDuration[] list_StatesDurationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime finishDate {
            get {
                return this.finishDateField;
            }
            set {
                if ((this.finishDateField.Equals(value) != true)) {
                    this.finishDateField = value;
                    this.RaisePropertyChanged("finishDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIT_Reports.WServiceReference.wsSimpleItem[] list_ED {
            get {
                return this.list_EDField;
            }
            set {
                if ((object.ReferenceEquals(this.list_EDField, value) != true)) {
                    this.list_EDField = value;
                    this.RaisePropertyChanged("list_ED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIT_Reports.WServiceReference.WorkStateMessage[] list_SCADAMessages {
            get {
                return this.list_SCADAMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.list_SCADAMessagesField, value) != true)) {
                    this.list_SCADAMessagesField = value;
                    this.RaisePropertyChanged("list_SCADAMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIT_Reports.WServiceReference.WStateNDuration[] list_StatesDurations {
            get {
                return this.list_StatesDurationsField;
            }
            set {
                if ((object.ReferenceEquals(this.list_StatesDurationsField, value) != true)) {
                    this.list_StatesDurationsField = value;
                    this.RaisePropertyChanged("list_StatesDurations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WStateNDuration", Namespace="http://schemas.datacontract.org/2004/07/SIT_classLib")]
    [System.SerializableAttribute()]
    public partial class WStateNDuration : SIT_Reports.WServiceReference.wsSimpleItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double durationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double durationBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string edField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double duration {
            get {
                return this.durationField;
            }
            set {
                if ((this.durationField.Equals(value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double durationBase {
            get {
                return this.durationBaseField;
            }
            set {
                if ((this.durationBaseField.Equals(value) != true)) {
                    this.durationBaseField = value;
                    this.RaisePropertyChanged("durationBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ed {
            get {
                return this.edField;
            }
            set {
                if ((object.ReferenceEquals(this.edField, value) != true)) {
                    this.edField = value;
                    this.RaisePropertyChanged("ed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stateName {
            get {
                return this.stateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.stateNameField, value) != true)) {
                    this.stateNameField = value;
                    this.RaisePropertyChanged("stateName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsProducerType", Namespace="http://www.SITBusiness.com/SITBusiness_classLib/wsProducerType")]
    [System.SerializableAttribute()]
    public partial class wsProducerType : SIT_Reports.WServiceReference.wsSimpleItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProducerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerStreetBuildingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerCity {
            get {
                return this.ProducerCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerCityField, value) != true)) {
                    this.ProducerCityField = value;
                    this.RaisePropertyChanged("ProducerCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerCountry {
            get {
                return this.ProducerCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerCountryField, value) != true)) {
                    this.ProducerCountryField = value;
                    this.RaisePropertyChanged("ProducerCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProducerID {
            get {
                return this.ProducerIDField;
            }
            set {
                if ((this.ProducerIDField.Equals(value) != true)) {
                    this.ProducerIDField = value;
                    this.RaisePropertyChanged("ProducerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerName {
            get {
                return this.ProducerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerNameField, value) != true)) {
                    this.ProducerNameField = value;
                    this.RaisePropertyChanged("ProducerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerPhone {
            get {
                return this.ProducerPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerPhoneField, value) != true)) {
                    this.ProducerPhoneField = value;
                    this.RaisePropertyChanged("ProducerPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerState {
            get {
                return this.ProducerStateField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerStateField, value) != true)) {
                    this.ProducerStateField = value;
                    this.RaisePropertyChanged("ProducerState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerStreetBuilding {
            get {
                return this.ProducerStreetBuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerStreetBuildingField, value) != true)) {
                    this.ProducerStreetBuildingField = value;
                    this.RaisePropertyChanged("ProducerStreetBuilding");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsModelItem", Namespace="http://www.SITBusiness.com/SITBusiness_classLib/wsModelItem")]
    [System.SerializableAttribute()]
    public partial class wsModelItem : SIT_Reports.WServiceReference.wsSimpleItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CalibrationPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubSubModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubSubModelNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CalibrationPeriod {
            get {
                return this.CalibrationPeriodField;
            }
            set {
                if ((this.CalibrationPeriodField.Equals(value) != true)) {
                    this.CalibrationPeriodField = value;
                    this.RaisePropertyChanged("CalibrationPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModelID {
            get {
                return this.ModelIDField;
            }
            set {
                if ((this.ModelIDField.Equals(value) != true)) {
                    this.ModelIDField = value;
                    this.RaisePropertyChanged("ModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubModelID {
            get {
                return this.SubModelIDField;
            }
            set {
                if ((this.SubModelIDField.Equals(value) != true)) {
                    this.SubModelIDField = value;
                    this.RaisePropertyChanged("SubModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubModelName {
            get {
                return this.SubModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubModelNameField, value) != true)) {
                    this.SubModelNameField = value;
                    this.RaisePropertyChanged("SubModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubSubModelID {
            get {
                return this.SubSubModelIDField;
            }
            set {
                if ((this.SubSubModelIDField.Equals(value) != true)) {
                    this.SubSubModelIDField = value;
                    this.RaisePropertyChanged("SubSubModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubSubModelName {
            get {
                return this.SubSubModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubSubModelNameField, value) != true)) {
                    this.SubSubModelNameField = value;
                    this.RaisePropertyChanged("SubSubModelName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsMaintenance", Namespace="http://www.SITBusiness.com/SITBusiness_classLib/wsMaintenance")]
    [System.SerializableAttribute()]
    public partial class wsMaintenance : SIT_Reports.WServiceReference.wsSimpleItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string docNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime factDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string factNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> plannedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string plannedNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string docNo {
            get {
                return this.docNoField;
            }
            set {
                if ((object.ReferenceEquals(this.docNoField, value) != true)) {
                    this.docNoField = value;
                    this.RaisePropertyChanged("docNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime factDate {
            get {
                return this.factDateField;
            }
            set {
                if ((this.factDateField.Equals(value) != true)) {
                    this.factDateField = value;
                    this.RaisePropertyChanged("factDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string factName {
            get {
                return this.factNameField;
            }
            set {
                if ((object.ReferenceEquals(this.factNameField, value) != true)) {
                    this.factNameField = value;
                    this.RaisePropertyChanged("factName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> plannedDate {
            get {
                return this.plannedDateField;
            }
            set {
                if ((this.plannedDateField.Equals(value) != true)) {
                    this.plannedDateField = value;
                    this.RaisePropertyChanged("plannedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string plannedName {
            get {
                return this.plannedNameField;
            }
            set {
                if ((object.ReferenceEquals(this.plannedNameField, value) != true)) {
                    this.plannedNameField = value;
                    this.RaisePropertyChanged("plannedName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsCalibration", Namespace="http://www.SITBusiness.com/SITBusiness_classLib/wsCalibrate")]
    [System.SerializableAttribute()]
    public partial class wsCalibration : SIT_Reports.WServiceReference.wsSimpleItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string docNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime factDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> plannedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string docNo {
            get {
                return this.docNoField;
            }
            set {
                if ((object.ReferenceEquals(this.docNoField, value) != true)) {
                    this.docNoField = value;
                    this.RaisePropertyChanged("docNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime factDate {
            get {
                return this.factDateField;
            }
            set {
                if ((this.factDateField.Equals(value) != true)) {
                    this.factDateField = value;
                    this.RaisePropertyChanged("factDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> plannedDate {
            get {
                return this.plannedDateField;
            }
            set {
                if ((this.plannedDateField.Equals(value) != true)) {
                    this.plannedDateField = value;
                    this.RaisePropertyChanged("plannedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                if ((this.resultField.Equals(value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultName {
            get {
                return this.resultNameField;
            }
            set {
                if ((object.ReferenceEquals(this.resultNameField, value) != true)) {
                    this.resultNameField = value;
                    this.RaisePropertyChanged("resultName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int typeID {
            get {
                return this.typeIDField;
            }
            set {
                if ((this.typeIDField.Equals(value) != true)) {
                    this.typeIDField = value;
                    this.RaisePropertyChanged("typeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string typeName {
            get {
                return this.typeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.typeNameField, value) != true)) {
                    this.typeNameField = value;
                    this.RaisePropertyChanged("typeName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkStateMessage", Namespace="http://www.SITBusiness.com/SITBusiness_classLib/WorkStateMessage")]
    [System.SerializableAttribute()]
    public partial class WorkStateMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeBeginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongDescrRUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int msField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int msgNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int scadaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeBegin {
            get {
                return this.DateTimeBeginField;
            }
            set {
                if ((this.DateTimeBeginField.Equals(value) != true)) {
                    this.DateTimeBeginField = value;
                    this.RaisePropertyChanged("DateTimeBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeEnd {
            get {
                return this.DateTimeEndField;
            }
            set {
                if ((this.DateTimeEndField.Equals(value) != true)) {
                    this.DateTimeEndField = value;
                    this.RaisePropertyChanged("DateTimeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LongDescrRU {
            get {
                return this.LongDescrRUField;
            }
            set {
                if ((object.ReferenceEquals(this.LongDescrRUField, value) != true)) {
                    this.LongDescrRUField = value;
                    this.RaisePropertyChanged("LongDescrRU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ms {
            get {
                return this.msField;
            }
            set {
                if ((this.msField.Equals(value) != true)) {
                    this.msField = value;
                    this.RaisePropertyChanged("ms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int msgNr {
            get {
                return this.msgNrField;
            }
            set {
                if ((this.msgNrField.Equals(value) != true)) {
                    this.msgNrField = value;
                    this.RaisePropertyChanged("msgNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int scadaID {
            get {
                return this.scadaIDField;
            }
            set {
                if ((this.scadaIDField.Equals(value) != true)) {
                    this.scadaIDField = value;
                    this.RaisePropertyChanged("scadaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsPasspotrExtended", Namespace="http://www.SITBusiness.com/SITBusiness_classLib/wsPasspotrExtended")]
    [System.SerializableAttribute()]
    public partial class wsPasspotrExtended : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CalibrationPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CurrentStateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentStateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DevCompoundModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevDescrRUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DevIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevInvNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DevModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevModificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DevModificationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevPassportNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DevPlaceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevPlaceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevPlacePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevSubModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DevSubModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DevTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ImplementationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCalibratedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ProduceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProducerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerStreetBuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PurchaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] helper_DevDescrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIT_Reports.WServiceReference.wsProducerType[] list_ProducersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIT_Reports.WServiceReference.wsBaseItem[] tbl_ModelsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CalibrationPeriod {
            get {
                return this.CalibrationPeriodField;
            }
            set {
                if ((this.CalibrationPeriodField.Equals(value) != true)) {
                    this.CalibrationPeriodField = value;
                    this.RaisePropertyChanged("CalibrationPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CurrentStateID {
            get {
                return this.CurrentStateIDField;
            }
            set {
                if ((this.CurrentStateIDField.Equals(value) != true)) {
                    this.CurrentStateIDField = value;
                    this.RaisePropertyChanged("CurrentStateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentStateName {
            get {
                return this.CurrentStateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentStateNameField, value) != true)) {
                    this.CurrentStateNameField = value;
                    this.RaisePropertyChanged("CurrentStateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DevCompoundModelID {
            get {
                return this.DevCompoundModelIDField;
            }
            set {
                if ((this.DevCompoundModelIDField.Equals(value) != true)) {
                    this.DevCompoundModelIDField = value;
                    this.RaisePropertyChanged("DevCompoundModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevDescrRU {
            get {
                return this.DevDescrRUField;
            }
            set {
                if ((object.ReferenceEquals(this.DevDescrRUField, value) != true)) {
                    this.DevDescrRUField = value;
                    this.RaisePropertyChanged("DevDescrRU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DevID {
            get {
                return this.DevIDField;
            }
            set {
                if ((this.DevIDField.Equals(value) != true)) {
                    this.DevIDField = value;
                    this.RaisePropertyChanged("DevID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevInvNo {
            get {
                return this.DevInvNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DevInvNoField, value) != true)) {
                    this.DevInvNoField = value;
                    this.RaisePropertyChanged("DevInvNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevModel {
            get {
                return this.DevModelField;
            }
            set {
                if ((object.ReferenceEquals(this.DevModelField, value) != true)) {
                    this.DevModelField = value;
                    this.RaisePropertyChanged("DevModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DevModelID {
            get {
                return this.DevModelIDField;
            }
            set {
                if ((this.DevModelIDField.Equals(value) != true)) {
                    this.DevModelIDField = value;
                    this.RaisePropertyChanged("DevModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevModification {
            get {
                return this.DevModificationField;
            }
            set {
                if ((object.ReferenceEquals(this.DevModificationField, value) != true)) {
                    this.DevModificationField = value;
                    this.RaisePropertyChanged("DevModification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DevModificationID {
            get {
                return this.DevModificationIDField;
            }
            set {
                if ((this.DevModificationIDField.Equals(value) != true)) {
                    this.DevModificationIDField = value;
                    this.RaisePropertyChanged("DevModificationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevPassportNo {
            get {
                return this.DevPassportNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DevPassportNoField, value) != true)) {
                    this.DevPassportNoField = value;
                    this.RaisePropertyChanged("DevPassportNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevPath {
            get {
                return this.DevPathField;
            }
            set {
                if ((object.ReferenceEquals(this.DevPathField, value) != true)) {
                    this.DevPathField = value;
                    this.RaisePropertyChanged("DevPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DevPlaceID {
            get {
                return this.DevPlaceIDField;
            }
            set {
                if ((this.DevPlaceIDField.Equals(value) != true)) {
                    this.DevPlaceIDField = value;
                    this.RaisePropertyChanged("DevPlaceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevPlaceName {
            get {
                return this.DevPlaceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DevPlaceNameField, value) != true)) {
                    this.DevPlaceNameField = value;
                    this.RaisePropertyChanged("DevPlaceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevPlacePath {
            get {
                return this.DevPlacePathField;
            }
            set {
                if ((object.ReferenceEquals(this.DevPlacePathField, value) != true)) {
                    this.DevPlacePathField = value;
                    this.RaisePropertyChanged("DevPlacePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevSubModel {
            get {
                return this.DevSubModelField;
            }
            set {
                if ((object.ReferenceEquals(this.DevSubModelField, value) != true)) {
                    this.DevSubModelField = value;
                    this.RaisePropertyChanged("DevSubModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DevSubModelID {
            get {
                return this.DevSubModelIDField;
            }
            set {
                if ((this.DevSubModelIDField.Equals(value) != true)) {
                    this.DevSubModelIDField = value;
                    this.RaisePropertyChanged("DevSubModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DevTypeID {
            get {
                return this.DevTypeIDField;
            }
            set {
                if ((this.DevTypeIDField.Equals(value) != true)) {
                    this.DevTypeIDField = value;
                    this.RaisePropertyChanged("DevTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevTypeName {
            get {
                return this.DevTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DevTypeNameField, value) != true)) {
                    this.DevTypeNameField = value;
                    this.RaisePropertyChanged("DevTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ImplementationDate {
            get {
                return this.ImplementationDateField;
            }
            set {
                if ((this.ImplementationDateField.Equals(value) != true)) {
                    this.ImplementationDateField = value;
                    this.RaisePropertyChanged("ImplementationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCalibrated {
            get {
                return this.IsCalibratedField;
            }
            set {
                if ((this.IsCalibratedField.Equals(value) != true)) {
                    this.IsCalibratedField = value;
                    this.RaisePropertyChanged("IsCalibrated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ProduceDate {
            get {
                return this.ProduceDateField;
            }
            set {
                if ((this.ProduceDateField.Equals(value) != true)) {
                    this.ProduceDateField = value;
                    this.RaisePropertyChanged("ProduceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerCity {
            get {
                return this.ProducerCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerCityField, value) != true)) {
                    this.ProducerCityField = value;
                    this.RaisePropertyChanged("ProducerCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerCountry {
            get {
                return this.ProducerCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerCountryField, value) != true)) {
                    this.ProducerCountryField = value;
                    this.RaisePropertyChanged("ProducerCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProducerID {
            get {
                return this.ProducerIDField;
            }
            set {
                if ((this.ProducerIDField.Equals(value) != true)) {
                    this.ProducerIDField = value;
                    this.RaisePropertyChanged("ProducerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerName {
            get {
                return this.ProducerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerNameField, value) != true)) {
                    this.ProducerNameField = value;
                    this.RaisePropertyChanged("ProducerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerPhone {
            get {
                return this.ProducerPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerPhoneField, value) != true)) {
                    this.ProducerPhoneField = value;
                    this.RaisePropertyChanged("ProducerPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerState {
            get {
                return this.ProducerStateField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerStateField, value) != true)) {
                    this.ProducerStateField = value;
                    this.RaisePropertyChanged("ProducerState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProducerStreetBuilding {
            get {
                return this.ProducerStreetBuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerStreetBuildingField, value) != true)) {
                    this.ProducerStreetBuildingField = value;
                    this.RaisePropertyChanged("ProducerStreetBuilding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PurchaseDate {
            get {
                return this.PurchaseDateField;
            }
            set {
                if ((this.PurchaseDateField.Equals(value) != true)) {
                    this.PurchaseDateField = value;
                    this.RaisePropertyChanged("PurchaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] helper_DevDescr {
            get {
                return this.helper_DevDescrField;
            }
            set {
                if ((object.ReferenceEquals(this.helper_DevDescrField, value) != true)) {
                    this.helper_DevDescrField = value;
                    this.RaisePropertyChanged("helper_DevDescr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIT_Reports.WServiceReference.wsProducerType[] list_Producers {
            get {
                return this.list_ProducersField;
            }
            set {
                if ((object.ReferenceEquals(this.list_ProducersField, value) != true)) {
                    this.list_ProducersField = value;
                    this.RaisePropertyChanged("list_Producers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIT_Reports.WServiceReference.wsBaseItem[] tbl_Models {
            get {
                return this.tbl_ModelsField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_ModelsField, value) != true)) {
                    this.tbl_ModelsField = value;
                    this.RaisePropertyChanged("tbl_Models");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="WServiceReference.WService")]
    public interface WService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/TestService", ReplyAction="urn:WService/TestServiceResponse")]
        int TestService();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_TestDBConnection", ReplyAction="urn:WService/ws_TestDBConnectionResponse")]
        int ws_TestDBConnection(out string OpStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_TestAuthConnection", ReplyAction="urn:WService/ws_TestAuthConnectionResponse")]
        int ws_TestAuthConnection(out string OpStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectDBTree", ReplyAction="urn:WService/ws_selectDBTreeResponse")]
        SIT_Reports.WServiceReference.DBTree ws_selectDBTree(out string OpStatus, int TreeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectTreeItemsList", ReplyAction="urn:WService/ws_selectTreeItemsListResponse")]
        SIT_Reports.WServiceReference.wsBaseItem[] ws_selectTreeItemsList(out string OpStatus, out string Path, System.Nullable<int> ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_deleteTreeItem", ReplyAction="urn:WService/ws_deleteTreeItemResponse")]
        int ws_deleteTreeItem(out string OpStatus, int[] IDlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_insertNode", ReplyAction="urn:WService/ws_insertNodeResponse")]
        int ws_insertNode(out string OpStatus, string NodeName, System.Nullable<int> ParentID, bool IsCalibrated);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_updateNode", ReplyAction="urn:WService/ws_updateNodeResponse")]
        int ws_updateNode(out string OpStatus, int NodeID, string NodeName, System.Nullable<int> ParentID, string LinkToIcon, bool IsCalibrated);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_deleteNode", ReplyAction="urn:WService/ws_deleteNodeResponse")]
        int ws_deleteNode(out string OpStatus, int NodeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectDevDescrList", ReplyAction="urn:WService/ws_selectDevDescrListResponse")]
        string[] ws_selectDevDescrList(out string OpStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_helperTypesList", ReplyAction="urn:WService/ws_helperTypesListResponse")]
        string[] ws_helperTypesList(out string OpStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_moveItems", ReplyAction="urn:WService/ws_moveItemsResponse")]
        int ws_moveItems(out string OpStatus, int ID, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectPassport", ReplyAction="urn:WService/ws_selectPassportResponse")]
        SIT_Reports.WServiceReference.wsPasspotrExtended ws_selectPassport(out string OpStatus, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectPassport_EX", ReplyAction="urn:WService/ws_selectPassport_EXResponse")]
        SIT_Reports.WServiceReference.wsPasspotrExtended ws_selectPassport_EX(out string OpStatus, System.Nullable<int> ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_checkPassportProducer", ReplyAction="urn:WService/ws_checkPassportProducerResponse")]
        int ws_checkPassportProducer(out int OpValue, out string OpStatus, SIT_Reports.WServiceReference.wsProducerType P);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_insertPassport", ReplyAction="urn:WService/ws_insertPassportResponse")]
        int ws_insertPassport(out string OpStatus, SIT_Reports.WServiceReference.wsPasspotrExtended p, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_updatePassport", ReplyAction="urn:WService/ws_updatePassportResponse")]
        int ws_updatePassport(out string OpStatus, SIT_Reports.WServiceReference.wsPasspotrExtended p);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectDeviceParents", ReplyAction="urn:WService/ws_selectDeviceParentsResponse")]
        string ws_selectDeviceParents(out string OpStatus, System.Nullable<int> ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectPassportsList", ReplyAction="urn:WService/ws_selectPassportsListResponse")]
        SIT_Reports.WServiceReference.wsPasspotrExtended[] ws_selectPassportsList(out string OpStatus, System.Nullable<int> TypeID, System.Nullable<int> PlaceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectModelsList", ReplyAction="urn:WService/ws_selectModelsListResponse")]
        SIT_Reports.WServiceReference.wsSimpleItem[] ws_selectModelsList(out string OpStatus, System.Nullable<int> ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectModelParents", ReplyAction="urn:WService/ws_selectModelParentsResponse")]
        SIT_Reports.WServiceReference.wsSimpleItem[] ws_selectModelParents(out string OpStatus, System.Nullable<int> ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectSubModelsList", ReplyAction="urn:WService/ws_selectSubModelsListResponse")]
        SIT_Reports.WServiceReference.wsSimpleItem[] ws_selectSubModelsList(out string OpStatus, System.Nullable<int> ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectModificationsList", ReplyAction="urn:WService/ws_selectModificationsListResponse")]
        SIT_Reports.WServiceReference.wsSimpleItem[] ws_selectModificationsList(out string OpStatus, System.Nullable<int> ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectDBTreeModels", ReplyAction="urn:WService/ws_selectDBTreeModelsResponse")]
        SIT_Reports.WServiceReference.DBTree ws_selectDBTreeModels(out string OpStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectModels", ReplyAction="urn:WService/ws_selectModelsResponse")]
        SIT_Reports.WServiceReference.wsModelItem[] ws_selectModels(out string OpStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectProducersList", ReplyAction="urn:WService/ws_selectProducersListResponse")]
        SIT_Reports.WServiceReference.wsProducerType[] ws_selectProducersList(out string OpStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectProducersData", ReplyAction="urn:WService/ws_selectProducersDataResponse")]
        SIT_Reports.WServiceReference.wsProducerType ws_selectProducersData(out string OpStatus, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_updateProducer", ReplyAction="urn:WService/ws_updateProducerResponse")]
        int ws_updateProducer(out string OpStatus, SIT_Reports.WServiceReference.wsProducerType LocalProducer);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_insertProducer", ReplyAction="urn:WService/ws_insertProducerResponse")]
        int ws_insertProducer(out string OpStatus, SIT_Reports.WServiceReference.wsProducerType LocalProducer);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_checkProducer", ReplyAction="urn:WService/ws_checkProducerResponse")]
        SIT_Reports.WServiceReference.wsSimpleItem[] ws_checkProducer(out int OpValue, out string OpStatus, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_deleteProducer", ReplyAction="urn:WService/ws_deleteProducerResponse")]
        int ws_deleteProducer(out int OpValue, out string OpStatus, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectPlaces", ReplyAction="urn:WService/ws_selectPlacesResponse")]
        SIT_Reports.WServiceReference.wsBaseItem[] ws_selectPlaces(out string OpStatus, System.Nullable<int> _ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_insertPlace", ReplyAction="urn:WService/ws_insertPlaceResponse")]
        int ws_insertPlace(out string OpStatus, string Name, System.Nullable<int> parentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_deletePlace", ReplyAction="urn:WService/ws_deletePlaceResponse")]
        int ws_deletePlace(out string OpStatus, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectDBTreePlaces", ReplyAction="urn:WService/ws_selectDBTreePlacesResponse")]
        SIT_Reports.WServiceReference.DBTree ws_selectDBTreePlaces(out string OpStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectPlaceParents", ReplyAction="urn:WService/ws_selectPlaceParentsResponse")]
        string ws_selectPlaceParents(out string OpStatus, System.Nullable<int> ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectDevListByPlace", ReplyAction="urn:WService/ws_selectDevListByPlaceResponse")]
        SIT_Reports.WServiceReference.wsBaseItem[] ws_selectDevListByPlace(out string OpStatus, out string Path, System.Nullable<int> ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectNextCalibrations", ReplyAction="urn:WService/ws_selectNextCalibrationsResponse")]
        SIT_Reports.WServiceReference.wsCalibration[] ws_selectNextCalibrations(out string OpStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectDeviceCalibrations", ReplyAction="urn:WService/ws_selectDeviceCalibrationsResponse")]
        SIT_Reports.WServiceReference.wsCalibration[] ws_selectDeviceCalibrations(out string OpStatus, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_insertCalibration", ReplyAction="urn:WService/ws_insertCalibrationResponse")]
        int ws_insertCalibration(out string OpStatus, SIT_Reports.WServiceReference.wsCalibration c);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectCalibrationTypes", ReplyAction="urn:WService/ws_selectCalibrationTypesResponse")]
        SIT_Reports.WServiceReference.wsSimpleItem[] ws_selectCalibrationTypes(out string OpStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_ins_upd_Period", ReplyAction="urn:WService/ws_ins_upd_PeriodResponse")]
        int ws_ins_upd_Period(out string OpStatus, int _id, int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectNextMaintenances", ReplyAction="urn:WService/ws_selectNextMaintenancesResponse")]
        SIT_Reports.WServiceReference.wsMaintenance[] ws_selectNextMaintenances(out string OpStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectDeviceMaintenances", ReplyAction="urn:WService/ws_selectDeviceMaintenancesResponse")]
        SIT_Reports.WServiceReference.wsMaintenance[] ws_selectDeviceMaintenances(out string OpStatus, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:WService/ws_selectDeviceWorkStates", ReplyAction="urn:WService/ws_selectDeviceWorkStatesResponse")]
        SIT_Reports.WServiceReference.wsWorkState ws_selectDeviceWorkStates(out string OpStatus, int id, System.DateTime beginDate, System.DateTime endDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WServiceChannel : SIT_Reports.WServiceReference.WService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WServiceClient : System.ServiceModel.ClientBase<SIT_Reports.WServiceReference.WService>, SIT_Reports.WServiceReference.WService {
        
        public WServiceClient() {
        }
        
        public WServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int TestService() {
            return base.Channel.TestService();
        }
        
        public int ws_TestDBConnection(out string OpStatus) {
            return base.Channel.ws_TestDBConnection(out OpStatus);
        }
        
        public int ws_TestAuthConnection(out string OpStatus) {
            return base.Channel.ws_TestAuthConnection(out OpStatus);
        }
        
        public SIT_Reports.WServiceReference.DBTree ws_selectDBTree(out string OpStatus, int TreeID) {
            return base.Channel.ws_selectDBTree(out OpStatus, TreeID);
        }
        
        public SIT_Reports.WServiceReference.wsBaseItem[] ws_selectTreeItemsList(out string OpStatus, out string Path, System.Nullable<int> ID) {
            return base.Channel.ws_selectTreeItemsList(out OpStatus, out Path, ID);
        }
        
        public int ws_deleteTreeItem(out string OpStatus, int[] IDlist) {
            return base.Channel.ws_deleteTreeItem(out OpStatus, IDlist);
        }
        
        public int ws_insertNode(out string OpStatus, string NodeName, System.Nullable<int> ParentID, bool IsCalibrated) {
            return base.Channel.ws_insertNode(out OpStatus, NodeName, ParentID, IsCalibrated);
        }
        
        public int ws_updateNode(out string OpStatus, int NodeID, string NodeName, System.Nullable<int> ParentID, string LinkToIcon, bool IsCalibrated) {
            return base.Channel.ws_updateNode(out OpStatus, NodeID, NodeName, ParentID, LinkToIcon, IsCalibrated);
        }
        
        public int ws_deleteNode(out string OpStatus, int NodeID) {
            return base.Channel.ws_deleteNode(out OpStatus, NodeID);
        }
        
        public string[] ws_selectDevDescrList(out string OpStatus) {
            return base.Channel.ws_selectDevDescrList(out OpStatus);
        }
        
        public string[] ws_helperTypesList(out string OpStatus) {
            return base.Channel.ws_helperTypesList(out OpStatus);
        }
        
        public int ws_moveItems(out string OpStatus, int ID, string xml) {
            return base.Channel.ws_moveItems(out OpStatus, ID, xml);
        }
        
        public SIT_Reports.WServiceReference.wsPasspotrExtended ws_selectPassport(out string OpStatus, int ID) {
            return base.Channel.ws_selectPassport(out OpStatus, ID);
        }
        
        public SIT_Reports.WServiceReference.wsPasspotrExtended ws_selectPassport_EX(out string OpStatus, System.Nullable<int> ID) {
            return base.Channel.ws_selectPassport_EX(out OpStatus, ID);
        }
        
        public int ws_checkPassportProducer(out int OpValue, out string OpStatus, SIT_Reports.WServiceReference.wsProducerType P) {
            return base.Channel.ws_checkPassportProducer(out OpValue, out OpStatus, P);
        }
        
        public int ws_insertPassport(out string OpStatus, SIT_Reports.WServiceReference.wsPasspotrExtended p, int ID) {
            return base.Channel.ws_insertPassport(out OpStatus, p, ID);
        }
        
        public int ws_updatePassport(out string OpStatus, SIT_Reports.WServiceReference.wsPasspotrExtended p) {
            return base.Channel.ws_updatePassport(out OpStatus, p);
        }
        
        public string ws_selectDeviceParents(out string OpStatus, System.Nullable<int> ID) {
            return base.Channel.ws_selectDeviceParents(out OpStatus, ID);
        }
        
        public SIT_Reports.WServiceReference.wsPasspotrExtended[] ws_selectPassportsList(out string OpStatus, System.Nullable<int> TypeID, System.Nullable<int> PlaceID) {
            return base.Channel.ws_selectPassportsList(out OpStatus, TypeID, PlaceID);
        }
        
        public SIT_Reports.WServiceReference.wsSimpleItem[] ws_selectModelsList(out string OpStatus, System.Nullable<int> ID) {
            return base.Channel.ws_selectModelsList(out OpStatus, ID);
        }
        
        public SIT_Reports.WServiceReference.wsSimpleItem[] ws_selectModelParents(out string OpStatus, System.Nullable<int> ID) {
            return base.Channel.ws_selectModelParents(out OpStatus, ID);
        }
        
        public SIT_Reports.WServiceReference.wsSimpleItem[] ws_selectSubModelsList(out string OpStatus, System.Nullable<int> ID) {
            return base.Channel.ws_selectSubModelsList(out OpStatus, ID);
        }
        
        public SIT_Reports.WServiceReference.wsSimpleItem[] ws_selectModificationsList(out string OpStatus, System.Nullable<int> ID) {
            return base.Channel.ws_selectModificationsList(out OpStatus, ID);
        }
        
        public SIT_Reports.WServiceReference.DBTree ws_selectDBTreeModels(out string OpStatus) {
            return base.Channel.ws_selectDBTreeModels(out OpStatus);
        }
        
        public SIT_Reports.WServiceReference.wsModelItem[] ws_selectModels(out string OpStatus) {
            return base.Channel.ws_selectModels(out OpStatus);
        }
        
        public SIT_Reports.WServiceReference.wsProducerType[] ws_selectProducersList(out string OpStatus) {
            return base.Channel.ws_selectProducersList(out OpStatus);
        }
        
        public SIT_Reports.WServiceReference.wsProducerType ws_selectProducersData(out string OpStatus, int ID) {
            return base.Channel.ws_selectProducersData(out OpStatus, ID);
        }
        
        public int ws_updateProducer(out string OpStatus, SIT_Reports.WServiceReference.wsProducerType LocalProducer) {
            return base.Channel.ws_updateProducer(out OpStatus, LocalProducer);
        }
        
        public int ws_insertProducer(out string OpStatus, SIT_Reports.WServiceReference.wsProducerType LocalProducer) {
            return base.Channel.ws_insertProducer(out OpStatus, LocalProducer);
        }
        
        public SIT_Reports.WServiceReference.wsSimpleItem[] ws_checkProducer(out int OpValue, out string OpStatus, int ID) {
            return base.Channel.ws_checkProducer(out OpValue, out OpStatus, ID);
        }
        
        public int ws_deleteProducer(out int OpValue, out string OpStatus, int ID) {
            return base.Channel.ws_deleteProducer(out OpValue, out OpStatus, ID);
        }
        
        public SIT_Reports.WServiceReference.wsBaseItem[] ws_selectPlaces(out string OpStatus, System.Nullable<int> _ID) {
            return base.Channel.ws_selectPlaces(out OpStatus, _ID);
        }
        
        public int ws_insertPlace(out string OpStatus, string Name, System.Nullable<int> parentID) {
            return base.Channel.ws_insertPlace(out OpStatus, Name, parentID);
        }
        
        public int ws_deletePlace(out string OpStatus, int ID) {
            return base.Channel.ws_deletePlace(out OpStatus, ID);
        }
        
        public SIT_Reports.WServiceReference.DBTree ws_selectDBTreePlaces(out string OpStatus) {
            return base.Channel.ws_selectDBTreePlaces(out OpStatus);
        }
        
        public string ws_selectPlaceParents(out string OpStatus, System.Nullable<int> ID) {
            return base.Channel.ws_selectPlaceParents(out OpStatus, ID);
        }
        
        public SIT_Reports.WServiceReference.wsBaseItem[] ws_selectDevListByPlace(out string OpStatus, out string Path, System.Nullable<int> ID) {
            return base.Channel.ws_selectDevListByPlace(out OpStatus, out Path, ID);
        }
        
        public SIT_Reports.WServiceReference.wsCalibration[] ws_selectNextCalibrations(out string OpStatus) {
            return base.Channel.ws_selectNextCalibrations(out OpStatus);
        }
        
        public SIT_Reports.WServiceReference.wsCalibration[] ws_selectDeviceCalibrations(out string OpStatus, int id) {
            return base.Channel.ws_selectDeviceCalibrations(out OpStatus, id);
        }
        
        public int ws_insertCalibration(out string OpStatus, SIT_Reports.WServiceReference.wsCalibration c) {
            return base.Channel.ws_insertCalibration(out OpStatus, c);
        }
        
        public SIT_Reports.WServiceReference.wsSimpleItem[] ws_selectCalibrationTypes(out string OpStatus) {
            return base.Channel.ws_selectCalibrationTypes(out OpStatus);
        }
        
        public int ws_ins_upd_Period(out string OpStatus, int _id, int period) {
            return base.Channel.ws_ins_upd_Period(out OpStatus, _id, period);
        }
        
        public SIT_Reports.WServiceReference.wsMaintenance[] ws_selectNextMaintenances(out string OpStatus) {
            return base.Channel.ws_selectNextMaintenances(out OpStatus);
        }
        
        public SIT_Reports.WServiceReference.wsMaintenance[] ws_selectDeviceMaintenances(out string OpStatus, int id) {
            return base.Channel.ws_selectDeviceMaintenances(out OpStatus, id);
        }
        
        public SIT_Reports.WServiceReference.wsWorkState ws_selectDeviceWorkStates(out string OpStatus, int id, System.DateTime beginDate, System.DateTime endDate) {
            return base.Channel.ws_selectDeviceWorkStates(out OpStatus, id, beginDate, endDate);
        }
    }
}
